version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: meet-room-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - meet-room-network

  app:
    build: .
    container_name: meet-room-app
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - meet-room-network

volumes:
  redis-data:

networks:
  meet-room-network:
    driver: bridge
