  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8

      - name: Run black (auto-format)
        run: black .

      - name: Run isort (auto-sort imports)
        run: isort .

      - name: Run flake8 (lint check only)
        run: flake8 .
